"""
Production Scheduling & Optimization SQLAlchemy ORM Models
Includes ProductionSchedule and ScheduledTask entities generated by OR-Tools CP-SAT.
"""

import uuid
from datetime import datetime
from typing import TYPE_CHECKING, List, Optional
from sqlalchemy import Boolean, DateTime, Float, ForeignKey, Integer, String, Text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base, TimestampMixin, UUIDPrimaryKeyMixin

if TYPE_CHECKING:
    from app.models.production import Machine, ProductionOrder, Worker
    from app.models.user import User


class ProductionSchedule(Base, UUIDPrimaryKeyMixin, TimestampMixin):
    """
    ProductionSchedule entity representing an optimized manufacturing plan
    computed by the OR-Tools CP-SAT solver for a specific user workspace.
    """
    __tablename__ = "production_schedules"

    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    name: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
        default="Optimized Workshop Schedule",
    )
    start_date: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
    )
    horizon_days: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=14,
    )
    solver_status: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        default="FEASIBLE",
        index=True,
    )
    makespan_hours: Mapped[float] = mapped_column(
        Float,
        nullable=False,
        default=0.0,
    )
    total_orders_scheduled: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=0,
    )
    total_orders_unscheduled: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=0,
    )
    worker_utilization_pct: Mapped[float] = mapped_column(
        Float,
        nullable=False,
        default=0.0,
    )
    machine_utilization_pct: Mapped[float] = mapped_column(
        Float,
        nullable=False,
        default=0.0,
    )
    runtime_seconds: Mapped[float] = mapped_column(
        Float,
        nullable=False,
        default=0.0,
    )

    # Relationships
    user: Mapped["User"] = relationship("User", back_populates="production_schedules")
    tasks: Mapped[List["ScheduledTask"]] = relationship(
        "ScheduledTask",
        back_populates="schedule",
        cascade="all, delete-orphan",
        order_by="ScheduledTask.start_time.asc()",
    )

    def __repr__(self) -> str:
        return f"<ProductionSchedule id={self.id} name='{self.name}' status='{self.solver_status}' makespan={self.makespan_hours}h>"


class ScheduledTask(Base, UUIDPrimaryKeyMixin, TimestampMixin):
    """
    ScheduledTask entity representing a discrete, conflict-free manufacturing operation
    allocated to a specific artisan and/or machine with precise start and end timestamps.
    """
    __tablename__ = "scheduled_tasks"

    schedule_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("production_schedules.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    order_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("production_orders.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    worker_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("workers.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    machine_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("machines.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    operation_name: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
    )
    start_time: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        index=True,
    )
    end_time: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        index=True,
    )
    duration_hours: Mapped[float] = mapped_column(
        Float,
        nullable=False,
    )
    sequence_order: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=1,
    )
    is_overdue: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=False,
    )

    # Relationships
    schedule: Mapped["ProductionSchedule"] = relationship("ProductionSchedule", back_populates="tasks")
    order: Mapped["ProductionOrder"] = relationship("ProductionOrder")
    worker: Mapped[Optional["Worker"]] = relationship("Worker")
    machine: Mapped[Optional["Machine"]] = relationship("Machine")

    def __repr__(self) -> str:
        return f"<ScheduledTask id={self.id} order_id={self.order_id} op='{self.operation_name}' start={self.start_time} end={self.end_time}>"
